"""release_check_tables

Revision ID: 7862eab74dc3
Revises: 1fc147f0e9be
Create Date: 2026-10-06 11:34:35.236560

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7862eab74dc3"
down_revision: str | Sequence[str] | None = "1fc147f0e9be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("release_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_release_checks_post_id"), "release_checks", ["post_id"], unique=False)
    op.create_table(
        "paragraph_flags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=False),
        sa.Column("paragraph_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("proposed_fix", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["check_id"], ["release_checks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["paragraph_id"], ["post_paragraphs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paragraph_flags_check_id"), "paragraph_flags", ["check_id"], unique=False
    )
    op.create_index(
        op.f("ix_paragraph_flags_paragraph_id"), "paragraph_flags", ["paragraph_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paragraph_flags_paragraph_id"), table_name="paragraph_flags")
    op.drop_index(op.f("ix_paragraph_flags_check_id"), table_name="paragraph_flags")
    op.drop_table("paragraph_flags")
    op.drop_index(op.f("ix_release_checks_post_id"), table_name="release_checks")
    op.drop_table("release_checks")
    # ### end Alembic commands ###
